/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    products: Product;
    'product-bundles': ProductBundle;
    categories: Category;
    pages: Page;
    orders: Order;
    'gallery-images': GalleryImage;
    faqs: Faq;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    products: ProductsSelect<false> | ProductsSelect<true>;
    'product-bundles': ProductBundlesSelect<false> | ProductBundlesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    'gallery-images': GalleryImagesSelect<false> | GalleryImagesSelect<true>;
    faqs: FaqsSelect<false> | FaqsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    home: Home;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Alt-tekst til billedet. Bruges for tilgængelighed og vises hvis billedet ikke kan indlæses.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  /**
   * Produktets navn, som det vises på hjemmesiden.
   */
  name: string;
  /**
   * Bruges i URL'en, fx "plastikstol" giver /udlejning/plastikstol.
   */
  slug: string;
  /**
   * Kort beskrivelse af produktet, vises på produktsiden.
   */
  description?: string | null;
  /**
   * Produktets pris pr. stk. i kr.
   */
  price: number;
  /**
   * Hovedbillede. Vises som udgangspunkt på produktsiden og i lister.
   */
  image?: (number | null) | Media;
  /**
   * Andre billeder af produktet, fx andre farver. Udfyld "Matcher valgmulighed" med teksten fra en værdi under Valgmuligheder (fx "Grå"), så billedet vises automatisk når den valgmulighed vælges.
   */
  gallery?:
    | {
        image: number | Media;
        /**
         * Valgfrit. Skal matche en værdi under Valgmuligheder præcist, fx "Grå".
         */
        matchesVariantValue?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * De kategorier produktet vises under.
   */
  categories?: (number | Category)[] | null;
  /**
   * Fx farve, eller type hvis produktet er bestik (gaffel/ske/kniv). Hver gruppe vises som en dropdown på produktsiden.
   */
  variants?:
    | {
        /**
         * Fx "Farve" eller "Type"
         */
        label: string;
        options: {
          /**
           * Fx "Rød" eller "Gaffel".
           */
          value: string;
          id?: string | null;
        }[];
        id?: string | null;
      }[]
    | null;
  /**
   * Vises som "Måske synes du også om" nederst på produktsiden.
   */
  relatedProducts?: (number | Product)[] | null;
  /**
   * Bestem om produktet er synligt og kan bestilles på hjemmesiden.
   */
  active?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  /**
   * Kategoriens navn, som det vises på hjemmesiden.
   */
  name: string;
  /**
   * Skal være unik på tværs af ALLE kategorier, ikke kun søskende-kategorier. Hvis navnet allerede findes i en anden gruppe (fx "Plastik" under både Stole og Bestik), så gør sluggen tydelig, fx "stole-plastik" og "bestik-plastik".
   */
  slug: string;
  /**
   * Lad stå tomt for en topniveau-kategori, eller vælg en kategori for at gøre denne til en underkategori.
   */
  parent?: (number | null) | Category;
  /**
   * Bestem om kategorien er synlig og kan vælges på hjemmesiden.
   */
  active?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-bundles".
 */
export interface ProductBundle {
  id: number;
  /**
   * Pakkens navn, som det vises på hjemmesiden.
   */
  name: string;
  /**
   * Bruges i URL'en, fx "fest-50" giver /pakketilbud/fest-50.
   */
  slug: string;
  /**
   * Kort beskrivelse af pakken, vises på pakkesiden.
   */
  description?: string | null;
  /**
   * Hovedbillede. Vises som udgangspunkt på pakkesiden og i lister.
   */
  image?: (number | null) | Media;
  /**
   * Andre billeder af pakken.
   */
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * De produkter og antal, pakken indeholder.
   */
  productItems: {
    /**
     * Produktet, der indgår i pakken.
     */
    product: number | Product;
    /**
     * Antal af produktet i pakken.
     */
    quantity: number;
    id?: string | null;
  }[];
  /**
   * Pakkens samlede pris i kr.
   */
  price: number;
  /**
   * Bestem om pakken er synlig og kan bestilles på hjemmesiden.
   */
  active?: boolean | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Titel, der vises øverst på siden og bruges i admin-panelet.
   */
  title: string;
  /**
   * Bruges i URL'en, fx "lejebetingelser" giver /lejebetingelser.
   */
  slug: string;
  /**
   * Sidens indhold.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  /**
   * Kundens fulde navn.
   */
  customerName: string;
  /**
   * Kundens e-mailadresse. Bruges til at sende ordrebekræftelse.
   */
  customerEmail: string;
  /**
   * Kundens telefonnummer.
   */
  customerPhone?: string | null;
  /**
   * Firmanavn, hvis ordren er til en virksomhed.
   */
  companyName?: string | null;
  /**
   * Vælg om kunden afhenter selv eller får leveret til en adresse.
   */
  deliveryMethod?: ('pickup' | 'delivery') | null;
  /**
   * Leveringsadresse. Udfyldes kun hvis leveringsmetoden er "Levering til adresse".
   */
  deliveryAddress?: {
    /**
     * Vejnavn og husnummer.
     */
    street?: string | null;
    /**
     * Postnummer.
     */
    postalCode?: string | null;
    /**
     * By.
     */
    city?: string | null;
    /**
     * Landekode, fx "DK".
     */
    country?: string | null;
  };
  /**
   * Markér hvis faktureringsadressen er den samme som leveringsadressen.
   */
  billingSameAsDelivery?: boolean | null;
  /**
   * Faktureringsadresse. Udfyldes kun hvis den afviger fra leveringsadressen.
   */
  billingAddress?: {
    /**
     * Firmanavn på fakturaen, hvis relevant.
     */
    companyName?: string | null;
    /**
     * Navn på fakturaen.
     */
    name?: string | null;
    /**
     * Vejnavn og husnummer.
     */
    street?: string | null;
    /**
     * Postnummer.
     */
    postalCode?: string | null;
    /**
     * By.
     */
    city?: string | null;
    /**
     * Landekode, fx "DK".
     */
    country?: string | null;
  };
  /**
   * Om kunden har accepteret handelsbetingelserne ved bestilling.
   */
  termsAccepted?: boolean | null;
  /**
   * Datoen for kundens arrangement.
   */
  eventDate?: string | null;
  /**
   * Eventuel kommentar eller særlige ønsker fra kunden.
   */
  comment?: string | null;
  /**
   * Produkterne og pakkerne i ordren.
   */
  items: {
    /**
     * Det bestilte produkt eller pakketilbud.
     */
    item:
      | {
          relationTo: 'products';
          value: number | Product;
        }
      | {
          relationTo: 'product-bundles';
          value: number | ProductBundle;
        };
    /**
     * Antal bestilt.
     */
    quantity: number;
    /**
     * Fx "Farve: Rød, Type: Gaffel"
     */
    selectedOptions?: string | null;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-images".
 */
export interface GalleryImage {
  id: number;
  /**
   * Bruges som billedets alt-tekst og som billedtekst i galleriet.
   */
  title: string;
  /**
   * Billedet, der vises i galleriet.
   */
  image: number | Media;
  /**
   * Inkluder dette billede i det roterende hero-billede på forsiden.
   */
  showInHero?: boolean | null;
  /**
   * Lavere tal vises først, både i hero-rotationen og galleriet.
   */
  order?: number | null;
  /**
   * Bestem om billedet vises på hjemmesiden.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs".
 */
export interface Faq {
  id: number;
  /**
   * Spørgsmålet, som det vises i FAQ-listen.
   */
  question: string;
  /**
   * Svaret, der vises når spørgsmålet foldes ud.
   */
  answer: string;
  /**
   * Lavere tal vises først.
   */
  order?: number | null;
  /**
   * Bestem om spørgsmålet vises på hjemmesiden.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'product-bundles';
        value: number | ProductBundle;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'gallery-images';
        value: number | GalleryImage;
      } | null)
    | ({
        relationTo: 'faqs';
        value: number | Faq;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  price?: T;
  image?: T;
  gallery?:
    | T
    | {
        image?: T;
        matchesVariantValue?: T;
        id?: T;
      };
  categories?: T;
  variants?:
    | T
    | {
        label?: T;
        options?:
          | T
          | {
              value?: T;
              id?: T;
            };
        id?: T;
      };
  relatedProducts?: T;
  active?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-bundles_select".
 */
export interface ProductBundlesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  image?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  productItems?:
    | T
    | {
        product?: T;
        quantity?: T;
        id?: T;
      };
  price?: T;
  active?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  parent?: T;
  active?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  customerName?: T;
  customerEmail?: T;
  customerPhone?: T;
  companyName?: T;
  deliveryMethod?: T;
  deliveryAddress?:
    | T
    | {
        street?: T;
        postalCode?: T;
        city?: T;
        country?: T;
      };
  billingSameAsDelivery?: T;
  billingAddress?:
    | T
    | {
        companyName?: T;
        name?: T;
        street?: T;
        postalCode?: T;
        city?: T;
        country?: T;
      };
  termsAccepted?: T;
  eventDate?: T;
  comment?: T;
  items?:
    | T
    | {
        item?: T;
        quantity?: T;
        selectedOptions?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery-images_select".
 */
export interface GalleryImagesSelect<T extends boolean = true> {
  title?: T;
  image?: T;
  showInHero?: T;
  order?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faqs_select".
 */
export interface FaqsSelect<T extends boolean = true> {
  question?: T;
  answer?: T;
  order?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  /**
   * Introduktionsteksten under overskriften på forsiden.
   */
  introduction?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  introduction?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}